"""add persisted observatory artifacts

Revision ID: 0afb97092513
Revises: 9ce6e382ab5d
Create Date: 2026-08-29 20:14:55.751486
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0afb97092513"
down_revision: str | None = "9ce6e382ab5d"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytical_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_type", sa.String(length=120), nullable=False),
        sa.Column("analysis_version", sa.String(length=40), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_id"],
            ["corpora.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["corpus_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytical_artifacts_artifact_type"),
        "analytical_artifacts",
        ["artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytical_artifacts_content_hash"),
        "analytical_artifacts",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytical_artifacts_corpus_id"),
        "analytical_artifacts",
        ["corpus_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytical_artifacts_fingerprint"),
        "analytical_artifacts",
        ["fingerprint"],
        unique=True,
    )
    op.create_index(
        op.f("ix_analytical_artifacts_run_id"), "analytical_artifacts", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_analytical_artifacts_snapshot_id"),
        "analytical_artifacts",
        ["snapshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytical_artifacts_snapshot_id"), table_name="analytical_artifacts")
    op.drop_index(op.f("ix_analytical_artifacts_run_id"), table_name="analytical_artifacts")
    op.drop_index(op.f("ix_analytical_artifacts_fingerprint"), table_name="analytical_artifacts")
    op.drop_index(op.f("ix_analytical_artifacts_corpus_id"), table_name="analytical_artifacts")
    op.drop_index(op.f("ix_analytical_artifacts_content_hash"), table_name="analytical_artifacts")
    op.drop_index(op.f("ix_analytical_artifacts_artifact_type"), table_name="analytical_artifacts")
    op.drop_table("analytical_artifacts")
    # ### end Alembic commands ###
