"""initial ontology

Revision ID: 0bde58ff4348
Revises:
Create Date: 2026-08-22 09:22:16.167038
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0bde58ff4348"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebook_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("codebook_key", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_codebook_versions_codebook_key"),
        "codebook_versions",
        ["codebook_key"],
        unique=False,
    )
    op.create_index(
        "uq_codebook_version", "codebook_versions", ["codebook_key", "version"], unique=True
    )
    op.create_table(
        "corpora",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("privacy_policy", sa.String(length=64), nullable=False),
        sa.Column("is_validated_language", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measurement_definitions",
        sa.Column("id", sa.String(length=120), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("unit_of_analysis", sa.String(length=80), nullable=False),
        sa.Column("epistemic_level", sa.String(length=40), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("goal", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpora.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_corpus_id"), "conversations", ["corpus_id"], unique=False
    )
    op.create_table(
        "corpus_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpora.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corpus_snapshots_corpus_id"), "corpus_snapshots", ["corpus_id"], unique=False
    )
    op.create_index(
        op.f("ix_corpus_snapshots_source_hash"), "corpus_snapshots", ["source_hash"], unique=False
    )
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("causal_status", sa.String(length=24), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_id"],
            ["corpora.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hypotheses_corpus_id"), "hypotheses", ["corpus_id"], unique=False)
    op.create_table(
        "participants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("pseudonym", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["corpus_id"], ["corpora.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_participants_corpus_id"), "participants", ["corpus_id"], unique=False)
    op.create_table(
        "retrieval_traces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("strategy", sa.String(length=80), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("returned_count", sa.Integer(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("result_refs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_id"],
            ["corpora.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_retrieval_traces_corpus_id"), "retrieval_traces", ["corpus_id"], unique=False
    )
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["corpus_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_runs_snapshot_id"), "analysis_runs", ["snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_analysis_runs_status"), "analysis_runs", ["status"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=False),
        sa.Column("sender_id", sa.String(length=36), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reply_to_external_id", sa.String(length=240), nullable=True),
        sa.Column("message_type", sa.String(length=40), nullable=False),
        sa.Column("source_tombstone", sa.Boolean(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_reply_to_external_id"), "messages", ["reply_to_external_id"], unique=False
    )
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_index(op.f("ix_messages_sent_at"), "messages", ["sent_at"], unique=False)
    op.create_index(
        "uq_message_conversation_external",
        "messages",
        ["conversation_id", "external_id"],
        unique=True,
    )
    op.create_table(
        "participant_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("participant_id", sa.String(length=36), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=240), nullable=False),
        sa.Column("display_name", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["participant_id"], ["participants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_identities_participant_id"),
        "participant_identities",
        ["participant_id"],
        unique=False,
    )
    op.create_index(
        "uq_identity_platform_external",
        "participant_identities",
        ["platform", "external_id"],
        unique=True,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("segmentation_version", sa.String(length=64), nullable=False),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gap_hours", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_conversation_id"), "sessions", ["conversation_id"], unique=False
    )
    op.create_table(
        "source_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("object_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["snapshot_id"], ["corpus_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_artifacts_sha256"), "source_artifacts", ["sha256"], unique=False
    )
    op.create_index(
        op.f("ix_source_artifacts_snapshot_id"), "source_artifacts", ["snapshot_id"], unique=False
    )
    op.create_table(
        "analysis_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_key", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_analysis_tasks_run_id"), "analysis_tasks", ["run_id"], unique=False)
    op.create_table(
        "annotations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("object_type", sa.String(length=40), nullable=False),
        sa.Column("object_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("raw_confidence", sa.Float(), nullable=True),
        sa.Column("calibrated_confidence", sa.Float(), nullable=True),
        sa.Column("alternatives", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["corpus_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_annotations_kind"), "annotations", ["kind"], unique=False)
    op.create_index(op.f("ix_annotations_object_id"), "annotations", ["object_id"], unique=False)
    op.create_index(
        op.f("ix_annotations_object_type"), "annotations", ["object_type"], unique=False
    )
    op.create_index(op.f("ix_annotations_run_id"), "annotations", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_annotations_snapshot_id"), "annotations", ["snapshot_id"], unique=False
    )
    op.create_table(
        "attachment_refs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attachment_refs_message_id"), "attachment_refs", ["message_id"], unique=False
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_episodes_session_id"), "episodes", ["session_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("hypothesis_id", sa.String(length=36), nullable=True),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("epistemic_level", sa.String(length=40), nullable=False),
        sa.Column("causal_status", sa.String(length=24), nullable=False),
        sa.Column("supporting_evidence", sa.JSON(), nullable=False),
        sa.Column("counterevidence", sa.JSON(), nullable=False),
        sa.Column("alternative_explanations", sa.JSON(), nullable=False),
        sa.Column("sensitivity_results", sa.JSON(), nullable=False),
        sa.Column("dependency_dag_root", sa.String(length=240), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypotheses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_hypothesis_id"), "findings", ["hypothesis_id"], unique=False)
    op.create_index(op.f("ix_findings_run_id"), "findings", ["run_id"], unique=False)
    op.create_table(
        "interaction_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("target_participant_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_participant_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interaction_events_actor_id"), "interaction_events", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_events_conversation_id"),
        "interaction_events",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interaction_events_event_type"), "interaction_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_events_message_id"), "interaction_events", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_interaction_events_occurred_at"),
        "interaction_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_table(
        "measurement_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=120), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("subject_type", sa.String(length=40), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["measurement_definitions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurement_results_definition_id"),
        "measurement_results",
        ["definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_results_run_id"), "measurement_results", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurement_results_subject_id"),
        "measurement_results",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_results_subject_type"),
        "measurement_results",
        ["subject_type"],
        unique=False,
    )
    op.create_table(
        "message_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision_kind", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_revisions_message_id"), "message_revisions", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_revisions_text_hash"), "message_revisions", ["text_hash"], unique=False
    )
    op.create_index(
        "uq_message_revision", "message_revisions", ["message_id", "revision_number"], unique=True
    )
    op.create_table(
        "model_invocations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model", sa.String(length=160), nullable=False),
        sa.Column("task", sa.String(length=120), nullable=False),
        sa.Column("privacy_policy", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_invocations_run_id"), "model_invocations", ["run_id"], unique=False
    )
    op.create_table(
        "dependency_fingerprints",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("dependency_type", sa.String(length=80), nullable=False),
        sa.Column("dependency_key", sa.String(length=240), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["analysis_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependency_fingerprints_fingerprint"),
        "dependency_fingerprints",
        ["fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dependency_fingerprints_task_id"),
        "dependency_fingerprints",
        ["task_id"],
        unique=False,
    )
    op.create_table(
        "episode_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("episode_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_episode_messages_episode_id"), "episode_messages", ["episode_id"], unique=False
    )
    op.create_index(
        op.f("ix_episode_messages_message_id"), "episode_messages", ["message_id"], unique=False
    )
    op.create_index(
        "uq_episode_message", "episode_messages", ["episode_id", "message_id"], unique=True
    )
    op.create_table(
        "response_relations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=False),
        sa.Column("target_message_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explicit", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_message_id"],
            ["messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_response_relations_source_message_id"),
        "response_relations",
        ["source_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_response_relations_target_message_id"),
        "response_relations",
        ["target_message_id"],
        unique=False,
    )
    op.create_table(
        "spans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("start_codepoint", sa.Integer(), nullable=False),
        sa.Column("end_codepoint", sa.Integer(), nullable=False),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("exact_text_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["revision_id"], ["message_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_spans_revision_id"), "spans", ["revision_id"], unique=False)
    op.create_table(
        "stance_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=False),
        sa.Column("holder_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("position", sa.String(length=24), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("certainty", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["holder_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("annotation_id"),
    )
    op.create_index(
        op.f("ix_stance_observations_holder_id"), "stance_observations", ["holder_id"], unique=False
    )
    op.create_index(
        op.f("ix_stance_observations_target_id"), "stance_observations", ["target_id"], unique=False
    )
    op.create_table(
        "utterances",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("start_codepoint", sa.Integer(), nullable=False),
        sa.Column("end_codepoint", sa.Integer(), nullable=False),
        sa.Column("exact_text", sa.Text(), nullable=False),
        sa.Column("exact_text_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["revision_id"], ["message_revisions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_utterances_revision_id"), "utterances", ["revision_id"], unique=False)
    op.create_table(
        "proposition_mentions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=False),
        sa.Column("utterance_id", sa.String(length=36), nullable=False),
        sa.Column("span_id", sa.String(length=36), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("proposition_type", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["span_id"],
            ["spans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["utterance_id"],
            ["utterances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("annotation_id"),
    )
    op.create_index(
        op.f("ix_proposition_mentions_span_id"), "proposition_mentions", ["span_id"], unique=False
    )
    op.create_index(
        op.f("ix_proposition_mentions_utterance_id"),
        "proposition_mentions",
        ["utterance_id"],
        unique=False,
    )
    op.create_table(
        "proposition_relations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_proposition_id", sa.String(length=36), nullable=False),
        sa.Column("target_proposition_id", sa.String(length=36), nullable=False),
        sa.Column("relation_type", sa.String(length=40), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_proposition_id"],
            ["proposition_mentions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_proposition_id"],
            ["proposition_mentions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("annotation_id"),
    )
    op.create_index(
        op.f("ix_proposition_relations_relation_type"),
        "proposition_relations",
        ["relation_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proposition_relations_source_proposition_id"),
        "proposition_relations",
        ["source_proposition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_proposition_relations_target_proposition_id"),
        "proposition_relations",
        ["target_proposition_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_proposition_relations_target_proposition_id"), table_name="proposition_relations"
    )
    op.drop_index(
        op.f("ix_proposition_relations_source_proposition_id"), table_name="proposition_relations"
    )
    op.drop_index(
        op.f("ix_proposition_relations_relation_type"), table_name="proposition_relations"
    )
    op.drop_table("proposition_relations")
    op.drop_index(op.f("ix_proposition_mentions_utterance_id"), table_name="proposition_mentions")
    op.drop_index(op.f("ix_proposition_mentions_span_id"), table_name="proposition_mentions")
    op.drop_table("proposition_mentions")
    op.drop_index(op.f("ix_utterances_revision_id"), table_name="utterances")
    op.drop_table("utterances")
    op.drop_index(op.f("ix_stance_observations_target_id"), table_name="stance_observations")
    op.drop_index(op.f("ix_stance_observations_holder_id"), table_name="stance_observations")
    op.drop_table("stance_observations")
    op.drop_index(op.f("ix_spans_revision_id"), table_name="spans")
    op.drop_table("spans")
    op.drop_index(op.f("ix_response_relations_target_message_id"), table_name="response_relations")
    op.drop_index(op.f("ix_response_relations_source_message_id"), table_name="response_relations")
    op.drop_table("response_relations")
    op.drop_index("uq_episode_message", table_name="episode_messages")
    op.drop_index(op.f("ix_episode_messages_message_id"), table_name="episode_messages")
    op.drop_index(op.f("ix_episode_messages_episode_id"), table_name="episode_messages")
    op.drop_table("episode_messages")
    op.drop_index(op.f("ix_dependency_fingerprints_task_id"), table_name="dependency_fingerprints")
    op.drop_index(
        op.f("ix_dependency_fingerprints_fingerprint"), table_name="dependency_fingerprints"
    )
    op.drop_table("dependency_fingerprints")
    op.drop_index(op.f("ix_model_invocations_run_id"), table_name="model_invocations")
    op.drop_table("model_invocations")
    op.drop_index("uq_message_revision", table_name="message_revisions")
    op.drop_index(op.f("ix_message_revisions_text_hash"), table_name="message_revisions")
    op.drop_index(op.f("ix_message_revisions_message_id"), table_name="message_revisions")
    op.drop_table("message_revisions")
    op.drop_index(op.f("ix_measurement_results_subject_type"), table_name="measurement_results")
    op.drop_index(op.f("ix_measurement_results_subject_id"), table_name="measurement_results")
    op.drop_index(op.f("ix_measurement_results_run_id"), table_name="measurement_results")
    op.drop_index(op.f("ix_measurement_results_definition_id"), table_name="measurement_results")
    op.drop_table("measurement_results")
    op.drop_index(op.f("ix_interaction_events_occurred_at"), table_name="interaction_events")
    op.drop_index(op.f("ix_interaction_events_message_id"), table_name="interaction_events")
    op.drop_index(op.f("ix_interaction_events_event_type"), table_name="interaction_events")
    op.drop_index(op.f("ix_interaction_events_conversation_id"), table_name="interaction_events")
    op.drop_index(op.f("ix_interaction_events_actor_id"), table_name="interaction_events")
    op.drop_table("interaction_events")
    op.drop_index(op.f("ix_findings_run_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_hypothesis_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_episodes_session_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index(op.f("ix_attachment_refs_message_id"), table_name="attachment_refs")
    op.drop_table("attachment_refs")
    op.drop_index(op.f("ix_annotations_snapshot_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_run_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_object_type"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_object_id"), table_name="annotations")
    op.drop_index(op.f("ix_annotations_kind"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(op.f("ix_analysis_tasks_run_id"), table_name="analysis_tasks")
    op.drop_table("analysis_tasks")
    op.drop_index(op.f("ix_source_artifacts_snapshot_id"), table_name="source_artifacts")
    op.drop_index(op.f("ix_source_artifacts_sha256"), table_name="source_artifacts")
    op.drop_table("source_artifacts")
    op.drop_index(op.f("ix_sessions_conversation_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("uq_identity_platform_external", table_name="participant_identities")
    op.drop_index(
        op.f("ix_participant_identities_participant_id"), table_name="participant_identities"
    )
    op.drop_table("participant_identities")
    op.drop_index("uq_message_conversation_external", table_name="messages")
    op.drop_index(op.f("ix_messages_sent_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_reply_to_external_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_analysis_runs_status"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_snapshot_id"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index(op.f("ix_retrieval_traces_corpus_id"), table_name="retrieval_traces")
    op.drop_table("retrieval_traces")
    op.drop_index(op.f("ix_participants_corpus_id"), table_name="participants")
    op.drop_table("participants")
    op.drop_index(op.f("ix_hypotheses_corpus_id"), table_name="hypotheses")
    op.drop_table("hypotheses")
    op.drop_index(op.f("ix_corpus_snapshots_source_hash"), table_name="corpus_snapshots")
    op.drop_index(op.f("ix_corpus_snapshots_corpus_id"), table_name="corpus_snapshots")
    op.drop_table("corpus_snapshots")
    op.drop_index(op.f("ix_conversations_corpus_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("measurement_definitions")
    op.drop_table("corpora")
    op.drop_index("uq_codebook_version", table_name="codebook_versions")
    op.drop_index(op.f("ix_codebook_versions_codebook_key"), table_name="codebook_versions")
    op.drop_table("codebook_versions")
    # ### end Alembic commands ###
