"""foundation 0.2 evidence state

Revision ID: a0227985f3fc
Revises: 0bde58ff4348
Create Date: 2026-08-25 15:59:35.587576
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a0227985f3fc"
down_revision: str | None = "0bde58ff4348"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codebook_artifacts",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "codebook_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("codebook_key", sa.String(length=120), nullable=False),
        sa.Column("semantic_version", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_hash"],
            ["codebook_artifacts.content_hash"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codebook_key", "semantic_version", name="uq_codebook_release"),
    )
    op.create_index(
        op.f("ix_codebook_releases_artifact_hash"),
        "codebook_releases",
        ["artifact_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_codebook_releases_codebook_key"),
        "codebook_releases",
        ["codebook_key"],
        unique=False,
    )
    op.create_table(
        "import_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("corpus_id", sa.String(length=36), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("source_namespace", sa.String(length=240), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("imported_messages", sa.Integer(), nullable=False),
        sa.Column("reused_messages", sa.Integer(), nullable=False),
        sa.Column("appended_revisions", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_id"],
            ["corpora.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_import_runs_corpus_id"), "import_runs", ["corpus_id"], unique=False)
    op.create_index(
        op.f("ix_import_runs_source_hash"), "import_runs", ["source_hash"], unique=False
    )
    op.create_index(op.f("ix_import_runs_status"), "import_runs", ["status"], unique=False)
    op.create_table(
        "derivation_edges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_type",
            "source_id",
            "target_type",
            "target_id",
            "relation",
            "run_id",
            name="uq_derivation_edge",
        ),
    )
    op.create_index(
        op.f("ix_derivation_edges_relation"), "derivation_edges", ["relation"], unique=False
    )
    op.create_index(
        op.f("ix_derivation_edges_run_id"), "derivation_edges", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_derivation_edges_source_id"), "derivation_edges", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_derivation_edges_source_type"), "derivation_edges", ["source_type"], unique=False
    )
    op.create_index(
        op.f("ix_derivation_edges_target_id"), "derivation_edges", ["target_id"], unique=False
    )
    op.create_index(
        op.f("ix_derivation_edges_target_type"), "derivation_edges", ["target_type"], unique=False
    )
    op.create_table(
        "annotation_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reviewer", sa.String(length=240), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotation_reviews_annotation_id"),
        "annotation_reviews",
        ["annotation_id"],
        unique=False,
    )
    op.create_table(
        "snapshot_message_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["revision_id"], ["message_revisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["corpus_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "message_id", name="uq_snapshot_message"),
        sa.UniqueConstraint("snapshot_id", "revision_id", name="uq_snapshot_revision"),
    )
    op.create_index(
        op.f("ix_snapshot_message_revisions_message_id"),
        "snapshot_message_revisions",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_snapshot_message_revisions_revision_id"),
        "snapshot_message_revisions",
        ["revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_snapshot_message_revisions_snapshot_id"),
        "snapshot_message_revisions",
        ["snapshot_id"],
        unique=False,
    )
    op.create_table(
        "epistemic_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("annotation_id", sa.String(length=36), nullable=False),
        sa.Column("holder_id", sa.String(length=36), nullable=False),
        sa.Column("proposition_id", sa.String(length=36), nullable=False),
        sa.Column("polarity", sa.String(length=24), nullable=False),
        sa.Column("commitment", sa.Float(), nullable=False),
        sa.Column("certainty", sa.Float(), nullable=False),
        sa.Column("evidential_basis", sa.String(length=80), nullable=False),
        sa.Column("attributed_source_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["attributed_source_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["holder_id"],
            ["participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposition_id"],
            ["proposition_mentions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("annotation_id"),
    )
    op.create_index(
        op.f("ix_epistemic_observations_attributed_source_id"),
        "epistemic_observations",
        ["attributed_source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epistemic_observations_holder_id"),
        "epistemic_observations",
        ["holder_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_epistemic_observations_proposition_id"),
        "epistemic_observations",
        ["proposition_id"],
        unique=False,
    )
    with op.batch_alter_table("annotations") as batch:
        batch.add_column(sa.Column("superseded_by", sa.String(length=36), nullable=True))
        batch.create_index("ix_annotations_superseded_by", ["superseded_by"])
        batch.create_foreign_key(
            "fk_annotations_superseded_by", "annotations", ["superseded_by"], ["id"]
        )
    with op.batch_alter_table("conversations") as batch:
        batch.add_column(sa.Column("source_namespace", sa.String(length=240), nullable=True))
    op.execute("UPDATE conversations SET source_namespace = platform || '-legacy'")
    with op.batch_alter_table("conversations") as batch:
        batch.alter_column("source_namespace", nullable=False)
        batch.create_index(
            "uq_conversation_source_identity",
            ["corpus_id", "platform", "source_namespace", "external_id"],
            unique=True,
        )
    with op.batch_alter_table("corpus_snapshots") as batch:
        batch.add_column(sa.Column("parent_snapshot_id", sa.String(length=36), nullable=True))
        batch.add_column(sa.Column("manifest_hash", sa.String(length=64), nullable=True))
    op.execute("UPDATE corpus_snapshots SET manifest_hash = source_hash")
    with op.batch_alter_table("corpus_snapshots") as batch:
        batch.alter_column("manifest_hash", nullable=False)
        batch.create_index("ix_corpus_snapshots_manifest_hash", ["manifest_hash"])
        batch.create_index("ix_corpus_snapshots_parent_snapshot_id", ["parent_snapshot_id"])
        batch.create_foreign_key(
            "fk_corpus_snapshots_parent", "corpus_snapshots", ["parent_snapshot_id"], ["id"]
        )
    with op.batch_alter_table("findings") as batch:
        batch.add_column(sa.Column("superseded_by", sa.String(length=36), nullable=True))
        batch.create_index("ix_findings_superseded_by", ["superseded_by"])
        batch.create_foreign_key("fk_findings_superseded_by", "findings", ["superseded_by"], ["id"])
    with op.batch_alter_table("measurement_results") as batch:
        batch.add_column(sa.Column("provenance", sa.JSON(), nullable=False, server_default="{}"))
        batch.add_column(sa.Column("superseded_by", sa.String(length=36), nullable=True))
        batch.create_index("ix_measurement_results_superseded_by", ["superseded_by"])
        batch.create_foreign_key(
            "fk_measurement_results_superseded_by",
            "measurement_results",
            ["superseded_by"],
            ["id"],
        )
    with op.batch_alter_table("messages") as batch:
        batch.add_column(sa.Column("source_local_timestamp", sa.String(length=80), nullable=True))
        batch.add_column(
            sa.Column("source_timezone_assumption", sa.String(length=120), nullable=True)
        )
        batch.add_column(sa.Column("resolved_timestamp", sa.DateTime(timezone=True), nullable=True))
        batch.add_column(sa.Column("resolution_confidence", sa.Float(), nullable=True))
    op.execute(
        "UPDATE messages SET source_local_timestamp = CAST(sent_at AS VARCHAR), "
        "source_timezone_assumption = 'LEGACY_UNKNOWN', resolved_timestamp = sent_at, "
        "resolution_confidence = 0.0"
    )
    with op.batch_alter_table("messages") as batch:
        batch.alter_column("source_local_timestamp", nullable=False)
        batch.alter_column("resolved_timestamp", nullable=False)
        batch.alter_column("resolution_confidence", nullable=False)
        batch.create_index("ix_messages_resolved_timestamp", ["resolved_timestamp"])
    with op.batch_alter_table("participant_identities") as batch:
        batch.add_column(sa.Column("corpus_id", sa.String(length=36), nullable=True))
        batch.add_column(sa.Column("source_namespace", sa.String(length=240), nullable=True))
        batch.drop_index("uq_identity_platform_external")
    op.execute(
        "UPDATE participant_identities SET corpus_id = "
        "(SELECT corpus_id FROM participants WHERE participants.id = participant_id), "
        "source_namespace = platform || '-legacy'"
    )
    with op.batch_alter_table("participant_identities") as batch:
        batch.alter_column("corpus_id", nullable=False)
        batch.alter_column("source_namespace", nullable=False)
        batch.create_index("ix_participant_identities_corpus_id", ["corpus_id"])
        batch.create_index(
            "uq_identity_corpus_namespace_external",
            ["corpus_id", "platform", "source_namespace", "external_id"],
            unique=True,
        )
        batch.create_foreign_key(
            "fk_participant_identities_corpus",
            "corpora",
            ["corpus_id"],
            ["id"],
            ondelete="CASCADE",
        )
    with op.batch_alter_table("retrieval_traces") as batch:
        batch.add_column(sa.Column("snapshot_id", sa.String(length=36), nullable=True))
    op.execute(
        "UPDATE retrieval_traces SET snapshot_id = "
        "(SELECT id FROM corpus_snapshots WHERE corpus_id = retrieval_traces.corpus_id "
        "ORDER BY created_at DESC LIMIT 1)"
    )
    with op.batch_alter_table("retrieval_traces") as batch:
        batch.alter_column("snapshot_id", nullable=False)
        batch.create_index("ix_retrieval_traces_snapshot_id", ["snapshot_id"])
        batch.create_foreign_key(
            "fk_retrieval_traces_snapshot", "corpus_snapshots", ["snapshot_id"], ["id"]
        )
    with op.batch_alter_table("stance_observations") as batch:
        batch.add_column(
            sa.Column("target_weight", sa.Float(), nullable=False, server_default="1.0")
        )
        batch.add_column(
            sa.Column(
                "resolution_status", sa.String(length=24), nullable=False, server_default="RESOLVED"
            )
        )
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute(
            "CREATE INDEX ix_message_revisions_fts_ru ON message_revisions "
            "USING gin (to_tsvector('russian'::regconfig, text))"
        )
        op.execute(
            "CREATE INDEX ix_message_revisions_text_trgm ON message_revisions "
            "USING gin (text gin_trgm_ops)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index("ix_message_revisions_text_trgm", table_name="message_revisions")
        op.drop_index("ix_message_revisions_fts_ru", table_name="message_revisions")
    with op.batch_alter_table("stance_observations") as batch:
        batch.drop_column("resolution_status")
        batch.drop_column("target_weight")
    with op.batch_alter_table("retrieval_traces") as batch:
        batch.drop_constraint("fk_retrieval_traces_snapshot", type_="foreignkey")
        batch.drop_index("ix_retrieval_traces_snapshot_id")
        batch.drop_column("snapshot_id")
    with op.batch_alter_table("participant_identities") as batch:
        batch.drop_constraint("fk_participant_identities_corpus", type_="foreignkey")
        batch.drop_index("uq_identity_corpus_namespace_external")
        batch.drop_index("ix_participant_identities_corpus_id")
        batch.create_index(
            "uq_identity_platform_external", ["platform", "external_id"], unique=True
        )
        batch.drop_column("source_namespace")
        batch.drop_column("corpus_id")
    with op.batch_alter_table("messages") as batch:
        batch.drop_index("ix_messages_resolved_timestamp")
        batch.drop_column("resolution_confidence")
        batch.drop_column("resolved_timestamp")
        batch.drop_column("source_timezone_assumption")
        batch.drop_column("source_local_timestamp")
    with op.batch_alter_table("measurement_results") as batch:
        batch.drop_constraint("fk_measurement_results_superseded_by", type_="foreignkey")
        batch.drop_index("ix_measurement_results_superseded_by")
        batch.drop_column("superseded_by")
        batch.drop_column("provenance")
    with op.batch_alter_table("findings") as batch:
        batch.drop_constraint("fk_findings_superseded_by", type_="foreignkey")
        batch.drop_index("ix_findings_superseded_by")
        batch.drop_column("superseded_by")
    with op.batch_alter_table("corpus_snapshots") as batch:
        batch.drop_constraint("fk_corpus_snapshots_parent", type_="foreignkey")
        batch.drop_index("ix_corpus_snapshots_parent_snapshot_id")
        batch.drop_index("ix_corpus_snapshots_manifest_hash")
        batch.drop_column("manifest_hash")
        batch.drop_column("parent_snapshot_id")
    with op.batch_alter_table("conversations") as batch:
        batch.drop_index("uq_conversation_source_identity")
        batch.drop_column("source_namespace")
    with op.batch_alter_table("annotations") as batch:
        batch.drop_constraint("fk_annotations_superseded_by", type_="foreignkey")
        batch.drop_index("ix_annotations_superseded_by")
        batch.drop_column("superseded_by")
    op.drop_index(
        op.f("ix_epistemic_observations_proposition_id"), table_name="epistemic_observations"
    )
    op.drop_index(op.f("ix_epistemic_observations_holder_id"), table_name="epistemic_observations")
    op.drop_index(
        op.f("ix_epistemic_observations_attributed_source_id"), table_name="epistemic_observations"
    )
    op.drop_table("epistemic_observations")
    op.drop_index(
        op.f("ix_snapshot_message_revisions_snapshot_id"), table_name="snapshot_message_revisions"
    )
    op.drop_index(
        op.f("ix_snapshot_message_revisions_revision_id"), table_name="snapshot_message_revisions"
    )
    op.drop_index(
        op.f("ix_snapshot_message_revisions_message_id"), table_name="snapshot_message_revisions"
    )
    op.drop_table("snapshot_message_revisions")
    op.drop_index(op.f("ix_annotation_reviews_annotation_id"), table_name="annotation_reviews")
    op.drop_table("annotation_reviews")
    op.drop_index(op.f("ix_derivation_edges_target_type"), table_name="derivation_edges")
    op.drop_index(op.f("ix_derivation_edges_target_id"), table_name="derivation_edges")
    op.drop_index(op.f("ix_derivation_edges_source_type"), table_name="derivation_edges")
    op.drop_index(op.f("ix_derivation_edges_source_id"), table_name="derivation_edges")
    op.drop_index(op.f("ix_derivation_edges_run_id"), table_name="derivation_edges")
    op.drop_index(op.f("ix_derivation_edges_relation"), table_name="derivation_edges")
    op.drop_table("derivation_edges")
    op.drop_index(op.f("ix_import_runs_status"), table_name="import_runs")
    op.drop_index(op.f("ix_import_runs_source_hash"), table_name="import_runs")
    op.drop_index(op.f("ix_import_runs_corpus_id"), table_name="import_runs")
    op.drop_table("import_runs")
    op.drop_index(op.f("ix_codebook_releases_codebook_key"), table_name="codebook_releases")
    op.drop_index(op.f("ix_codebook_releases_artifact_hash"), table_name="codebook_releases")
    op.drop_table("codebook_releases")
    op.drop_table("codebook_artifacts")
    # ### end Alembic commands ###
